objects:
  north_wall:
    type: cube
    length: 4
    width: 4
    height: 0.1
    position:
      - 0
      - 4
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 0
      - 1
      - 1
  south_wall:
    type: cube
    length: 4
    width: 4
    height: 0.1
    position:
      - 0
      - -4
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 0
      - 1
      - 1
  east_wall:
    type: cube
    length: 4
    width: 12
    height: 0.1
    position:
      - 4
      - 0
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 0
      - 1
      - 1
  west_wall:
    type: cube
    length: 4
    width: 12
    height: 0.1
    position:
      - -4
      - 0
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 0
      - 1
      - 1
  obstacle:
    type: cube
    length: 1.5
    width: 1.5
    height: 0.1
    position:
      - 0.25
      - 0.75
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 0
      - 1
      - 1
indicators:
  start:
    type: cylinder
    length: 0.25
    width: 0.25
    height: 0.0001
    position:
      - -1.5
      - 1.5
      - 0
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 1
      - 0
      - 0
      - 1
  goal:
    type: cylinder
    length: 0.25
    width: 0.25
    height: 0.0001
    position:
      - 1.5
      - 1.5
      - 0
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 1
      - 0
      - 1
agents:
  agent:
    type: cube
    length: 0.2
    width: 0.2
    height: 0.05
    position:
      - -1.5
      - 1.5
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.23
      - 0.23
      - 0.23
      - 1
    wheel_radius: 0.5