objects:
  north_wall:
    type: cube
    length: 4
    width: 4
    height: 0.1
    position:
      - 0
      - 4
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.2
      - 0.4
      - 0.6
      - 1
  south_wall:
    type: cube
    length: 4
    width: 4
    height: 0.1
    position:
      - 0
      - -4
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.2
      - 0.4
      - 0.6
      - 1
  east_wall:
    type: cube
    length: 4
    width: 12
    height: 0.1
    position:
      - 4
      - 0
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.2
      - 0.4
      - 0.6
      - 1
  west_wall:
    type: cube
    length: 4
    width: 12
    height: 0.1
    position:
      - -4
      - 0
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.2
      - 0.4
      - 0.6
      - 1
  obstacle:
    type: cube
    length: 1
    width: 1
    height: 0.1
    position:
      - 0
      - 0
      - 0.05
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.2
      - 0.4
      - 0.6
      - 1
indicators:
  start1:
    type: cube
    length: 0.25
    width: 0.05
    height: 0.01
    position:
      - -1.5
      - -0.15
      - 0.01
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 1
      - 0
      - 0
      - 1
  start2:
    type: cube
    length: 0.25
    width: 0.05
    height: 0.01
    position:
      - -1.5
      - 0.15
      - 0.01
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 1
      - 0
      - 0
      - 1
  start3:
    type: cube
    length: 0.05
    width: 0.35
    height: 0.01
    position:
      - -1.65
      - 0.0
      - 0.01
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 1
      - 0
      - 0
      - 1
  start4:
    type: cube
    length: 0.05
    width: 0.35
    height: 0.01
    position:
      - -1.35
      - 0.0
      - 0.01
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 1
      - 0
      - 0
      - 1
  goal:
    type: cylinder
    length: 0.05
    width: 0.05
    height: 0.5
    position:
      - 1.5
      - 0
      - 0.25
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0
      - 1
      - 0
      - 1
agent:
  type: cube
  length: 0.2
  width: 0.2
  height: 0.05
  position:
    - -1.5
    - 0
    - 0.05
  orientation:
    - 0
    - 0
    - 0
    - 1
  parent_frame: world
  color:
    - 0.23
    - 0.23
    - 0.23
    - 1
  max_phi: 0.7   # Angular turn rate
  min_v: 0.0     # Min linear velocity
  max_v: 0.5     # Max linear velocity
  min_time: 0.0  # Min duration to apply action
  max_time: 0.5  # Max duration to apply action
start:
  state:
    - -1.5  # x
    - 0    # y
    - 0    # theta
goals:
  goal:
    state:
      - 1.5  # x
      - 0    # y
      - 0    # theta
    covariance:
      - 0.03
      - 0.03
      - 1.0
real_dynamics_noise: 0.02
belief_dynamics_noise: 0.02
belief_observation_noise:
  - 0.001
cem_distribution: gaussian
n_cem_gmm_components: 2
goal_distribution: gaussian
m_projection: False
max_plan_steps: 100
horizon: 15
n_iters: 5
n_candidates: 20000
n_elite: 20
n_mpc_runs: 1
