objects:
  obstacle1:
    type: cylinder
    radius: 0.075
    length: 0.15
    width: 0.15
    height: 1.0
    position:
      - 0.3
      - 0.0
      - 0.5
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.9
      - 0.9
      - 0.9
      - 1
agent:
  max_delta: 0.1
start:
  state:
    -  0.0
    - -1.323
    -  0.0
    - -1.885
    -  0.0
    -  1.653
    -  0.794
indicators:
  goal:
    type: sphere
    length: 0.1
    width: 0.1
    height: 0.1
    position:
      - 0.52085
      - 0.0
      - 0.64820
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 1
      - 1
      - 0
      - 1
goals:
  goal:
    state:
      -  0.0
      -  -0.132
      -  0.0
      -  -1.687
      -  0.0
      -  1.653
      -  0.794
    covariance:
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
    position:
      - 0.52085
      - 0.0
      - 0.64820
    orientation:
      - 1.0
      - 0
      - 0
      - 0
real_dynamics_noise: 0.02
belief_dynamics_noise: 0.02
belief_observation_noise:
  - 0.001
cem_distribution: gaussian
goal_distribution: gaussian
m_projection: False
max_plan_steps: 50
horizon: 10
n_iters: 5
n_candidates: 20
n_elite: 5
n_mpc_runs: 1
