objects:
  obstacle1:
    type: cylinder
    radius: 0.05
    length: 0.1
    width: 0.1
    height: 1.0
    position:
      - 0.3
      - 0.0
      - 0.5
    orientation:
      - 0
      - 0
      - 0
      - 1
    parent_frame: world
    color:
      - 0.2
      - 0.4
      - 0.6
      - 1
agent:
  max_delta: 0.1

start:
  state:
    -  0.0
    - -1.422
    -  0.0
    - -2.315
    -  0.0
    -  1.653
    -  0.794
goals:
  goal:
    state:
      -  0.794
      -  0.033
      -  0.0
      -  -1.687
      -  -1.653
      -  1.653
      -  0.794
    covariance:
      - 0.03
      - 0.03
      - 0.03
      - 0.03
      - 0.03
      - 0.03
      - 0.03
goal_distribution: gaussian