name: kl
channels:
  - conda-forge
  - pytorch
dependencies:
  - pyyaml
  - tqdm
  - h5py
  - matplotlib
  - ipython
  - opencv
  - gpustat
  - scikit-learn
  - seaborn
  - pytorch=1.7.0
  - torchvision=0.8.1
  - pip
  - pip:
    - git+https://github.com/catkin/catkin_tools.git  # Needed for Python3 compatibility
    - python3-empy # Needed to build ROS msgs in catkin
    - rospkg       # Needed to run ROS scripts
    - pyquaternion
    - pybullet