name: kl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6  # Need < 3.7 because of boost building for opencv
  - qt=5.9.5    # Version needed to build rviz_textured_quads
  - pyyaml
  - tqdm
  - h5py
  - matplotlib
  - ipython
  - opencv
  - gpustat
  - scikit-learn
  - seaborn
  - pytorch=1.6.0
  - torchvision=0.7.0
  - pip
  - pip:
    - catkin_tools
    - torchsummary
    - empy         # Needed to build ROS msgs in catkin
    - rospkg       # Needed to run ROS scripts
    - dataclasses  # Needed for python3.6, will be included in python3.7
    - pyquaternion